
// This file was auto-generated by ML.NET Model Builder. 

// using cbb_learn.src.Games.Models;
// using cbb_learn.src.Stats.Models;
using cbb_learn.src.Stats.Models;
// using AwayScoreModel.ModelInput;
using Newtonsoft.Json;
using CsvHelper;
using System.Globalization;
// using System.Threading.Tasks;
using System.Net.Http;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AwayScoreModel.ConsoleApp
{
    class Program
    {
        public static async Task Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input

            SeasonStatsService seasonStatsService = new SeasonStatsService();
            var seasonStats = await seasonStatsService.GetSeasonStats("2", "201");

            // Console.WriteLine($"home: {seasonStats["home"]["GamesPlayed"]}");
            // Console.WriteLine($"away: {seasonStats["away"]["GamesPlayed"]}");

            var modelInputA = seasonStatsService.GetModelInput(seasonStats["B"], seasonStats["A"]);
            var modelInputB = seasonStatsService.GetModelInput(seasonStats["A"], seasonStats["B"]);

            Console.WriteLine($"Predicting away points for teamId=2 against teamId=201\n");

            var predictionResultA = AwayScoreModel.Predict(modelInputA);

            Console.WriteLine($"Predicted AwayPoints for teamId=2: {predictionResultA.Score}\n");

            Console.WriteLine($"Predicting away points for teamId=201 against teamId=2\n");

            var predictionResultB = AwayScoreModel.Predict(modelInputB);

            Console.WriteLine($"Predicted AwayPoints for teamId=201: {predictionResultB.Score}\n");

            Console.WriteLine("=============== End of process ===============");
        }
    }
}
