
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace AwayScoreModel.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            AwayScoreModel.ModelInput sampleData = new AwayScoreModel.ModelInput()
            {
                HomePoints = 93F,
                HomeBlocks = 10F,
                HomeDefensiveRebounds = 29F,
                HomeSteals = 9F,
                HomeTurnoverPoints = 19F,
                HomeDisqualifications = 0F,
                HomeFlagrantFouls = 0F,
                HomeFouls = 22F,
                HomeEjections = 0F,
                HomeTechnicalFouls = 0F,
                HomeRebounds = 39F,
                HomeAssistTurnoverRatio = 1.7F,
                HomeStealFoulRatio = 0.4090909F,
                HomeBlockFoulRatio = 0.45454547F,
                HomeTeamAssistTurnoverRatio = 0F,
                HomeStealTurnoverRatio = 0.9F,
                HomeGamesPlayed = 1F,
                HomeGamesStarted = 0F,
                HomeDoubleDouble = 0F,
                HomeTripleDouble = 0F,
                HomeAssists = 17F,
                HomeFieldGoals = 0.483333F,
                HomeFieldGoalsAttempted = 60F,
                HomeFieldGoalsMade = 29F,
                HomeFieldGoalPct = 48.333332F,
                HomeFreeThrows = 0.78125F,
                HomeFreeThrowPct = 78.125F,
                HomeFreeThrowsAttempted = 32F,
                HomeFreeThrowsMade = 25F,
                HomeOffensiveRebounds = 10F,
                HomeTurnovers = 10F,
                HomeThreePointFieldGoalsAttempted = 25F,
                HomeThreePointFieldGoalsMade = 10F,
                HomeTeamTurnovers = 0F,
                HomePointsInPaint = 36F,
                HomeFastBreakPoints = 18F,
                HomeOffensiveReboundPct = 0.32258064F,
                HomeEstimatedPossessions = 72.8F,
                HomePointsPerEstimatedPossessions = 1.2774725F,
                HomeThreePointFieldGoalPct = 40F,
                HomeTwoPointFieldGoalsMade = 19F,
                HomeTwoPointFieldGoalsAttempted = 35F,
                HomeTwoPointFieldGoalPct = 54.285717F,
                HomeShootingEfficiency = 0.56666666F,
                HomeScoringEfficiency = 1.55F,
                AwayBlocks = 3F,
                AwayDefensiveRebounds = 23F,
                AwaySteals = 6F,
                AwayTurnoverPoints = 11F,
                AwayDisqualifications = 1F,
                AwayFlagrantFouls = 0F,
                AwayFouls = 25F,
                AwayEjections = 0F,
                AwayTechnicalFouls = 0F,
                AwayRebounds = 30F,
                AwayAssistTurnoverRatio = 0.5F,
                AwayStealFoulRatio = 0.24F,
                AwayBlockFoulRatio = 0.12F,
                AwayTeamAssistTurnoverRatio = 8F,
                AwayStealTurnoverRatio = 0.375F,
                AwayGamesPlayed = 1F,
                AwayGamesStarted = 0F,
                AwayDoubleDouble = 0F,
                AwayTripleDouble = 0F,
                AwayAssists = 8F,
                AwayFieldGoals = 0.418182F,
                AwayFieldGoalsAttempted = 55F,
                AwayFieldGoalsMade = 23F,
                AwayFieldGoalPct = 41.81818F,
                AwayFreeThrows = 0.583333F,
                AwayFreeThrowPct = 58.333332F,
                AwayFreeThrowsAttempted = 24F,
                AwayFreeThrowsMade = 14F,
                AwayOffensiveRebounds = 7F,
                AwayTurnovers = 16F,
                AwayThreePointFieldGoalsAttempted = 20F,
                AwayThreePointFieldGoalsMade = 5F,
                AwayTeamTurnovers = 1F,
                AwayPointsInPaint = 32F,
                AwayFastBreakPoints = 15F,
                AwayOffensiveReboundPct = 0.21875F,
                AwayEstimatedPossessions = 74.6F,
                AwayPointsPerEstimatedPossessions = 0.8713137F,
                AwayThreePointFieldGoalPct = 25F,
                AwayTwoPointFieldGoalsMade = 18F,
                AwayTwoPointFieldGoalsAttempted = 35F,
                AwayTwoPointFieldGoalPct = 51.428574F,
                AwayShootingEfficiency = 0.46363637F,
                AwayScoringEfficiency = 1.1818181F,
            };

            Console.WriteLine("Using model to make single prediction -- Comparing actual AwayPoints with predicted AwayPoints from sample data...\n\n");


            Console.WriteLine($"HomePoints: {93F}");
            Console.WriteLine($"AwayPoints: {65F}");
            Console.WriteLine($"HomeBlocks: {10F}");
            Console.WriteLine($"HomeDefensiveRebounds: {29F}");
            Console.WriteLine($"HomeSteals: {9F}");
            Console.WriteLine($"HomeTurnoverPoints: {19F}");
            Console.WriteLine($"HomeDisqualifications: {0F}");
            Console.WriteLine($"HomeFlagrantFouls: {0F}");
            Console.WriteLine($"HomeFouls: {22F}");
            Console.WriteLine($"HomeEjections: {0F}");
            Console.WriteLine($"HomeTechnicalFouls: {0F}");
            Console.WriteLine($"HomeRebounds: {39F}");
            Console.WriteLine($"HomeAssistTurnoverRatio: {1.7F}");
            Console.WriteLine($"HomeStealFoulRatio: {0.4090909F}");
            Console.WriteLine($"HomeBlockFoulRatio: {0.45454547F}");
            Console.WriteLine($"HomeTeamAssistTurnoverRatio: {0F}");
            Console.WriteLine($"HomeStealTurnoverRatio: {0.9F}");
            Console.WriteLine($"HomeGamesPlayed: {1F}");
            Console.WriteLine($"HomeGamesStarted: {0F}");
            Console.WriteLine($"HomeDoubleDouble: {0F}");
            Console.WriteLine($"HomeTripleDouble: {0F}");
            Console.WriteLine($"HomeAssists: {17F}");
            Console.WriteLine($"HomeFieldGoals: {0.483333F}");
            Console.WriteLine($"HomeFieldGoalsAttempted: {60F}");
            Console.WriteLine($"HomeFieldGoalsMade: {29F}");
            Console.WriteLine($"HomeFieldGoalPct: {48.333332F}");
            Console.WriteLine($"HomeFreeThrows: {0.78125F}");
            Console.WriteLine($"HomeFreeThrowPct: {78.125F}");
            Console.WriteLine($"HomeFreeThrowsAttempted: {32F}");
            Console.WriteLine($"HomeFreeThrowsMade: {25F}");
            Console.WriteLine($"HomeOffensiveRebounds: {10F}");
            Console.WriteLine($"HomeTurnovers: {10F}");
            Console.WriteLine($"HomeThreePointFieldGoalsAttempted: {25F}");
            Console.WriteLine($"HomeThreePointFieldGoalsMade: {10F}");
            Console.WriteLine($"HomeTeamTurnovers: {0F}");
            Console.WriteLine($"HomePointsInPaint: {36F}");
            Console.WriteLine($"HomeFastBreakPoints: {18F}");
            Console.WriteLine($"HomeOffensiveReboundPct: {0.32258064F}");
            Console.WriteLine($"HomeEstimatedPossessions: {72.8F}");
            Console.WriteLine($"HomePointsPerEstimatedPossessions: {1.2774725F}");
            Console.WriteLine($"HomeThreePointFieldGoalPct: {40F}");
            Console.WriteLine($"HomeTwoPointFieldGoalsMade: {19F}");
            Console.WriteLine($"HomeTwoPointFieldGoalsAttempted: {35F}");
            Console.WriteLine($"HomeTwoPointFieldGoalPct: {54.285717F}");
            Console.WriteLine($"HomeShootingEfficiency: {0.56666666F}");
            Console.WriteLine($"HomeScoringEfficiency: {1.55F}");
            Console.WriteLine($"AwayBlocks: {3F}");
            Console.WriteLine($"AwayDefensiveRebounds: {23F}");
            Console.WriteLine($"AwaySteals: {6F}");
            Console.WriteLine($"AwayTurnoverPoints: {11F}");
            Console.WriteLine($"AwayDisqualifications: {1F}");
            Console.WriteLine($"AwayFlagrantFouls: {0F}");
            Console.WriteLine($"AwayFouls: {25F}");
            Console.WriteLine($"AwayEjections: {0F}");
            Console.WriteLine($"AwayTechnicalFouls: {0F}");
            Console.WriteLine($"AwayRebounds: {30F}");
            Console.WriteLine($"AwayAssistTurnoverRatio: {0.5F}");
            Console.WriteLine($"AwayStealFoulRatio: {0.24F}");
            Console.WriteLine($"AwayBlockFoulRatio: {0.12F}");
            Console.WriteLine($"AwayTeamAssistTurnoverRatio: {8F}");
            Console.WriteLine($"AwayStealTurnoverRatio: {0.375F}");
            Console.WriteLine($"AwayGamesPlayed: {1F}");
            Console.WriteLine($"AwayGamesStarted: {0F}");
            Console.WriteLine($"AwayDoubleDouble: {0F}");
            Console.WriteLine($"AwayTripleDouble: {0F}");
            Console.WriteLine($"AwayAssists: {8F}");
            Console.WriteLine($"AwayFieldGoals: {0.418182F}");
            Console.WriteLine($"AwayFieldGoalsAttempted: {55F}");
            Console.WriteLine($"AwayFieldGoalsMade: {23F}");
            Console.WriteLine($"AwayFieldGoalPct: {41.81818F}");
            Console.WriteLine($"AwayFreeThrows: {0.583333F}");
            Console.WriteLine($"AwayFreeThrowPct: {58.333332F}");
            Console.WriteLine($"AwayFreeThrowsAttempted: {24F}");
            Console.WriteLine($"AwayFreeThrowsMade: {14F}");
            Console.WriteLine($"AwayOffensiveRebounds: {7F}");
            Console.WriteLine($"AwayTurnovers: {16F}");
            Console.WriteLine($"AwayThreePointFieldGoalsAttempted: {20F}");
            Console.WriteLine($"AwayThreePointFieldGoalsMade: {5F}");
            Console.WriteLine($"AwayTeamTurnovers: {1F}");
            Console.WriteLine($"AwayPointsInPaint: {32F}");
            Console.WriteLine($"AwayFastBreakPoints: {15F}");
            Console.WriteLine($"AwayOffensiveReboundPct: {0.21875F}");
            Console.WriteLine($"AwayEstimatedPossessions: {74.6F}");
            Console.WriteLine($"AwayPointsPerEstimatedPossessions: {0.8713137F}");
            Console.WriteLine($"AwayThreePointFieldGoalPct: {25F}");
            Console.WriteLine($"AwayTwoPointFieldGoalsMade: {18F}");
            Console.WriteLine($"AwayTwoPointFieldGoalsAttempted: {35F}");
            Console.WriteLine($"AwayTwoPointFieldGoalPct: {51.428574F}");
            Console.WriteLine($"AwayShootingEfficiency: {0.46363637F}");
            Console.WriteLine($"AwayScoringEfficiency: {1.1818181F}");



            // Use the model and Prediction Engine to predict on new sample data
            var predictionResult = predEngine.Predict(sampleData);

            Console.WriteLine($"\n\nPredicted AwayPoints: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
